-- INITIALLY v2 — Puzzle Bank Seed Data
-- Generated from researched content (movies, proverbs, songs, books), 3+ words minimum
-- Total entries: movies=171, proverbs=139, songs=146, books=113

insert into puzzles (category, title, word_count, initials, hints, fun_fact) values
('movie', 'The Element of Crime', 4, 'T E O C', '{}'::jsonb, null),
('movie', 'The Spirit of the Beehive', 5, 'T S O T B', '{}'::jsonb, null),
('movie', 'The Double Life of Véronique', 5, 'T D L O V', '{}'::jsonb, null),
('movie', 'The Bitter Tears of Petra von Kant', 7, 'T B T O P V K', '{}'::jsonb, null),
('movie', 'The Sorrow and the Pity', 5, 'T S A T P', '{}'::jsonb, null),
('movie', 'The Long Day Closes', 4, 'T L D C', '{}'::jsonb, null),
('movie', 'The Night of the Hunter', 5, 'T N O T H', '{}'::jsonb, null),
('movie', 'The Day the Earth Stood Still', 6, 'T D T E S S', '{}'::jsonb, null),
('movie', 'The Man Who Fell to Earth', 6, 'T M W F T E', '{}'::jsonb, null),
('movie', 'The City of Lost Children', 5, 'T C O L C', '{}'::jsonb, null),
('movie', 'The Discreet Charm of the Bourgeoisie', 6, 'T D C O T B', '{}'::jsonb, null),
('movie', 'The Battle of Algiers', 4, 'T B O A', '{}'::jsonb, null),
('movie', 'The Marriage of Maria Braun', 5, 'T M O M B', '{}'::jsonb, null),
('movie', 'The Merchant of Four Seasons', 5, 'T M O F S', '{}'::jsonb, null),
('movie', 'The Wings of Desire', 4, 'T W O D', '{}'::jsonb, null),
('movie', 'The Lady from Shanghai', 4, 'T L F S', '{}'::jsonb, null),
('movie', 'The Man on the Eiffel Tower', 6, 'T M O T E T', '{}'::jsonb, null),
('movie', 'The Day of the Jackal', 5, 'T D O T J', '{}'::jsonb, null),
('movie', 'The Taking of Pelham One Two Three', 7, 'T T O P O T T', '{}'::jsonb, null),
('movie', 'The Man Who Would Be King', 6, 'T M W W B K', '{}'::jsonb, null),
('movie', 'The Outlaw Josey Wales', 4, 'T O J W', '{}'::jsonb, null),
('movie', 'The Long Good Friday', 4, 'T L G F', '{}'::jsonb, null),
('movie', 'The King of Comedy', 4, 'T K O C', '{}'::jsonb, null),
('movie', 'The Purple Rose of Cairo', 5, 'T P R O C', '{}'::jsonb, null),
('movie', 'The Last Temptation of Christ', 5, 'T L T O C', '{}'::jsonb, null),
('movie', 'The Last of the Mohicans', 5, 'T L O T M', '{}'::jsonb, null),
('movie', 'The Age of Innocence', 4, 'T A O I', '{}'::jsonb, null),
('movie', 'The Madness of King George', 5, 'T M O K G', '{}'::jsonb, null),
('movie', 'The Postman Always Rings Twice', 5, 'T P A R T', '{}'::jsonb, null),
('movie', 'The Bridges of Madison County', 5, 'T B O M C', '{}'::jsonb, null),
('movie', 'The People vs. Larry Flynt', 5, 'T P V L F', '{}'::jsonb, null),
('movie', 'The Thin Red Line', 4, 'T T R L', '{}'::jsonb, null),
('movie', 'The Cider House Rules', 4, 'T C H R', '{}'::jsonb, null),
('movie', 'The Talented Mr. Ripley', 4, 'T T M R', '{}'::jsonb, null),
('movie', 'The Man Who Wasn''t There', 5, 'T M W W T', '{}'::jsonb, null),
('movie', 'The Count of Monte Cristo', 5, 'T C O M C', '{}'::jsonb, null),
('movie', 'The Life of David Gale', 5, 'T L O D G', '{}'::jsonb, null),
('movie', 'The Fog of War', 4, 'T F O W', '{}'::jsonb, null),
('movie', 'The Life Aquatic with Steve Zissou', 6, 'T L A W S Z', '{}'::jsonb, null),
('movie', 'The Squid and the Whale', 5, 'T S A T W', '{}'::jsonb, null),
('movie', 'The Last King of Scotland', 5, 'T L K O S', '{}'::jsonb, null),
('movie', 'The Science of Sleep', 4, 'T S O S', '{}'::jsonb, null),
('movie', 'The Assassination of Jesse James by the Coward Robert Ford', 10, 'T A O J J B T C R F', '{}'::jsonb, null),
('movie', 'The Boy in the Striped Pyjamas', 6, 'T B I T S P', '{}'::jsonb, null),
('movie', 'The Tree of Life', 4, 'T T O L', '{}'::jsonb, null),
('movie', 'The Place Beyond the Pines', 5, 'T P B T P', '{}'::jsonb, null),
('movie', 'The Secret Life of Walter Mitty', 6, 'T S L O W M', '{}'::jsonb, null),
('movie', 'The Grand Budapest Hotel', 4, 'T G B H', '{}'::jsonb, null),
('movie', 'The Fault in Our Stars', 5, 'T F I O S', '{}'::jsonb, null),
('movie', 'The Theory of Everything', 4, 'T T O E', '{}'::jsonb, null),
('movie', 'The Ballad of Buster Scruggs', 5, 'T B O B S', '{}'::jsonb, null),
('movie', 'The Peanut Butter Falcon', 4, 'T P B F', '{}'::jsonb, null),
('movie', 'The Trial of the Chicago 7', 6, 'T T O T C', '{}'::jsonb, null),
('movie', 'The Power of the Dog', 5, 'T P O T D', '{}'::jsonb, null),
('movie', 'The Shape of Water', 4, 'T S O W', '{}'::jsonb, null),
('movie', 'The Tragedy of Macbeth', 4, 'T T O M', '{}'::jsonb, null),
('movie', 'The Banshees of Inisherin', 4, 'T B O I', '{}'::jsonb, null),
('movie', 'The Zone of Interest', 4, 'T Z O I', '{}'::jsonb, null),
('movie', 'The Ministry of Ungentlemanly Warfare', 5, 'T M O U W', '{}'::jsonb, null),
('movie', 'Eternal Sunshine of the Spotless Mind', 6, 'E S O T S M', '{}'::jsonb, null),
('movie', 'No Country for Old Men', 5, 'N C F O M', '{}'::jsonb, null),
('movie', 'There Will Be Blood', 4, 'T W B B', '{}'::jsonb, null),
('movie', 'Requiem for a Dream', 4, 'R F A D', '{}'::jsonb, null),
('movie', 'Close Encounters of the Third Kind', 6, 'C E O T T K', '{}'::jsonb, null),
('movie', 'Butch Cassidy and the Sundance Kid', 6, 'B C A T S K', '{}'::jsonb, null),
('movie', 'The Silence of the Lambs', 5, 'T S O T L', '{}'::jsonb, null),
('movie', 'The Nightmare Before Christmas', 4, 'T N B C', '{}'::jsonb, null),
('movie', 'The Texas Chain Saw Massacre', 5, 'T T C S M', '{}'::jsonb, null),
('movie', 'The Rocky Horror Picture Show', 5, 'T R H P S', '{}'::jsonb, null),
('movie', 'The Devil Wears Prada', 4, 'T D W P', '{}'::jsonb, null),
('movie', 'The Pursuit of Happyness', 4, 'T P O H', '{}'::jsonb, null),
('movie', 'The Sound of Music', 4, 'T S O M', '{}'::jsonb, null),
('movie', 'The Wizard of Oz', 4, 'T W O O', '{}'::jsonb, null),
('movie', 'The Good, the Bad and the Ugly', 7, 'T G T B A T U', '{}'::jsonb, null),
('movie', 'The Wolf of Wall Street', 5, 'T W O W S', '{}'::jsonb, null),
('movie', 'The Perks of Being a Wallflower', 6, 'T P O B A W', '{}'::jsonb, null),
('movie', 'The Cabin in the Woods', 5, 'T C I T W', '{}'::jsonb, null),
('movie', 'The Edge of Seventeen', 4, 'T E O S', '{}'::jsonb, null),
('movie', 'The Killing of a Sacred Deer', 6, 'T K O A S D', '{}'::jsonb, null),
('movie', 'The Lost City of Z', 5, 'T L C O Z', '{}'::jsonb, null),
('movie', 'The Other Side of the Wind', 6, 'T O S O T W', '{}'::jsonb, null),
('movie', 'The Secret in Their Eyes', 5, 'T S I T E', '{}'::jsonb, null),
('movie', 'The Way Way Back', 4, 'T W W B', '{}'::jsonb, null),
('movie', 'The Wonderful Story of Henry Sugar', 6, 'T W S O H S', '{}'::jsonb, null),
('movie', 'The Year of Living Dangerously', 5, 'T Y O L D', '{}'::jsonb, null),
('movie', 'Three Billboards Outside Ebbing, Missouri', 5, 'T B O E M', '{}'::jsonb, null),
('movie', 'Tinker Tailor Soldier Spy', 4, 'T T S S', '{}'::jsonb, null),
('movie', 'All Dogs Go to Heaven', 5, 'A D G T H', '{}'::jsonb, null),
('movie', 'An American Werewolf in London', 5, 'A A W I L', '{}'::jsonb, null),
('movie', 'As Good as It Gets', 5, 'A G A I G', '{}'::jsonb, null),
('movie', 'A League of Their Own', 5, 'A L O T O', '{}'::jsonb, null),
('movie', 'A Million Ways to Die in the West', 8, 'A M W T D I T W', '{}'::jsonb, null),
('movie', 'A Nightmare on Elm Street', 5, 'A N O E S', '{}'::jsonb, null),
('movie', 'A Walk to Remember', 4, 'A W T R', '{}'::jsonb, null),
('movie', 'And Justice for All', 4, 'A J F A', '{}'::jsonb, null),
('movie', 'Angels in the Outfield', 4, 'A I T O', '{}'::jsonb, null),
('movie', 'Are We There Yet?', 4, 'A W T Y', '{}'::jsonb, null),
('movie', 'Around the World in 80 Days', 6, 'A T W I D', '{}'::jsonb, null),
('movie', 'Boyz n the Hood', 4, 'B N T H', '{}'::jsonb, null),
('movie', 'Bringing Down the House', 4, 'B D T H', '{}'::jsonb, null),
('movie', 'Charlie and the Chocolate Factory', 5, 'C A T C F', '{}'::jsonb, null),
('movie', 'Cloudy with a Chance of Meatballs', 6, 'C W A C O M', '{}'::jsonb, null),
('movie', 'Confessions of a Teenage Drama Queen', 6, 'C O A T D Q', '{}'::jsonb, null),
('movie', 'Crouching Tiger, Hidden Dragon', 4, 'C T H D', '{}'::jsonb, null),
('movie', 'Dawn of the Dead', 4, 'D O T D', '{}'::jsonb, null),
('movie', 'Death at a Funeral', 4, 'D A A F', '{}'::jsonb, null),
('movie', 'Diary of a Wimpy Kid', 5, 'D O A W K', '{}'::jsonb, null),
('movie', 'Empire of the Sun', 4, 'E O T S', '{}'::jsonb, null),
('movie', 'Escape from New York', 4, 'E F N Y', '{}'::jsonb, null),
('movie', 'Everything Everywhere All at Once', 5, 'E E A A O', '{}'::jsonb, null),
('movie', 'Extremely Loud & Incredibly Close', 5, 'E L I C', '{}'::jsonb, null),
('movie', 'Ferris Bueller''s Day Off', 4, 'F B D O', '{}'::jsonb, null),
('movie', 'Flight of the Navigator', 4, 'F O T N', '{}'::jsonb, null),
('movie', 'Four Weddings and a Funeral', 5, 'F W A A F', '{}'::jsonb, null),
('movie', 'From Dusk till Dawn', 4, 'F D T D', '{}'::jsonb, null),
('movie', 'From Russia with Love', 4, 'F R W L', '{}'::jsonb, null),
('movie', 'Gangs of New York', 4, 'G O N Y', '{}'::jsonb, null),
('movie', 'Get Rich or Die Tryin''', 5, 'G R O D T', '{}'::jsonb, null),
('movie', 'Ghost in the Shell', 4, 'G I T S', '{}'::jsonb, null),
('movie', 'Gone in 60 Seconds', 4, 'G I S', '{}'::jsonb, null),
('movie', 'Good Night, and Good Luck', 5, 'G N A G L', '{}'::jsonb, null),
('movie', 'Harold & Kumar Go to White Castle', 7, 'H K G T W C', '{}'::jsonb, null),
('movie', 'He''s Just Not That Into You', 6, 'H J N T I Y', '{}'::jsonb, null),
('movie', 'How to Lose a Guy in 10 Days', 8, 'H T L A G I D', '{}'::jsonb, null),
('movie', 'How to Train Your Dragon', 5, 'H T T Y D', '{}'::jsonb, null),
('movie', 'I Know What You Did Last Summer', 7, 'I K W Y D L S', '{}'::jsonb, null),
('movie', 'In the Heart of the Sea', 6, 'I T H O T S', '{}'::jsonb, null),
('movie', 'In the Name of the Father', 6, 'I T N O T F', '{}'::jsonb, null),
('movie', 'Interview with the Vampire', 4, 'I W T V', '{}'::jsonb, null),
('movie', 'It''s a Wonderful Life', 4, 'I A W L', '{}'::jsonb, null),
('movie', 'Journey to the Center of the Earth', 7, 'J T T C O T E', '{}'::jsonb, null),
('movie', 'Just Go with It', 4, 'J G W I', '{}'::jsonb, null),
('movie', 'Legends of the Fall', 4, 'L O T F', '{}'::jsonb, null),
('movie', 'Lock, Stock and Two Smoking Barrels', 6, 'L S A T S B', '{}'::jsonb, null),
('movie', 'Looney Tunes: Back in Action', 5, 'L T B I A', '{}'::jsonb, null),
('movie', 'Lord of the Flies', 4, 'L O T F', '{}'::jsonb, null),
('movie', 'Love and Other Drugs', 4, 'L A O D', '{}'::jsonb, null),
('movie', 'My Big Fat Greek Wedding', 5, 'M B F G W', '{}'::jsonb, null),
('movie', 'Night at the Museum', 4, 'N A T M', '{}'::jsonb, null),
('movie', 'No Time to Die', 4, 'N T T D', '{}'::jsonb, null),
('movie', 'Not Another Teen Movie', 4, 'N A T M', '{}'::jsonb, null),
('movie', 'Now You See Me', 4, 'N Y S M', '{}'::jsonb, null),
('movie', 'O Brother, Where Art Thou?', 5, 'O B W A T', '{}'::jsonb, null),
('movie', 'Once Upon a Time in Hollywood', 6, 'O U A T I H', '{}'::jsonb, null),
('movie', 'Phantom of the Opera', 4, 'P O T O', '{}'::jsonb, null),
('movie', 'Planet of the Apes', 4, 'P O T A', '{}'::jsonb, null),
('movie', 'Robin Hood: Prince of Thieves', 5, 'R H P O T', '{}'::jsonb, null),
('movie', 'Romy and Michele''s High School Reunion', 6, 'R A M H S R', '{}'::jsonb, null),
('movie', 'Scott Pilgrim vs. the World', 5, 'S P V T W', '{}'::jsonb, null),
('movie', 'Shaun of the Dead', 4, 'S O T D', '{}'::jsonb, null),
('movie', 'Singin'' in the Rain', 4, 'S I T R', '{}'::jsonb, null),
('movie', 'Snow White and the Huntsman', 5, 'S W A T H', '{}'::jsonb, null),
('movie', 'Ten Things I Hate About You', 6, 'T T I H A Y', '{}'::jsonb, null),
('movie', 'The Land Before Time', 4, 'T L B T', '{}'::jsonb, null),
('movie', 'The Man in the Iron Mask', 6, 'T M I T I M', '{}'::jsonb, null),
('movie', 'The Day After Tomorrow', 4, 'T D A T', '{}'::jsonb, null),
('movie', 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe', 11, 'T C O N T L T W A T W', '{}'::jsonb, null),
('movie', 'The Curious Case of Benjamin Button', 6, 'T C C O B B', '{}'::jsonb, null),
('movie', 'The Assassination of Gianni Versace', 5, 'T A O G V', '{}'::jsonb, null),
('movie', 'Alexander and the Terrible, Horrible, No Good, Very Bad Day', 10, 'A A T T H N G V B D', '{}'::jsonb, null),
('movie', 'Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)', 11, 'B O P A T F E O O H Q', '{}'::jsonb, null),
('movie', 'Sweeney Todd: The Demon Barber of Fleet Street', 8, 'S T T D B O F S', '{}'::jsonb, null),
('movie', 'To Wong Foo, Thanks for Everything! Julie Newmar', 8, 'T W F T F E J N', '{}'::jsonb, null),
('movie', 'Master and Commander: The Far Side of the World', 9, 'M A C T F S O T W', '{}'::jsonb, null),
('movie', 'Percy Jackson & the Olympians: The Lightning Thief', 8, 'P J T O T L T', '{}'::jsonb, null),
('movie', 'The Hitchhiker''s Guide to the Galaxy', 6, 'T H G T T G', '{}'::jsonb, null),
('movie', 'The Hunger Games: Catching Fire', 5, 'T H G C F', '{}'::jsonb, null),
('movie', 'The League of Extraordinary Gentlemen', 5, 'T L O E G', '{}'::jsonb, null),
('movie', 'The Gods Must Be Crazy', 5, 'T G M B C', '{}'::jsonb, null),
('movie', 'The Fast and the Furious', 5, 'T F A T F', '{}'::jsonb, null),
('movie', 'The Dark Knight Rises', 4, 'T D K R', '{}'::jsonb, null),
('proverb', 'A bird in the hand is worth two in the bush', 11, 'A B I T H I W T I T B', '{}'::jsonb, null),
('proverb', 'A chain is only as strong as its weakest link', 10, 'A C I O A S A I W L', '{}'::jsonb, null),
('proverb', 'A fool and his money are soon parted', 8, 'A F A H M A S P', '{}'::jsonb, null),
('proverb', 'A friend in need is a friend indeed', 8, 'A F I N I A F I', '{}'::jsonb, null),
('proverb', 'A journey of a thousand miles begins with a single step', 11, 'A J O A T M B W A S S', '{}'::jsonb, null),
('proverb', 'A leopard cannot change its spots', 6, 'A L C C I S', '{}'::jsonb, null),
('proverb', 'A little knowledge is a dangerous thing', 7, 'A L K I A D T', '{}'::jsonb, null),
('proverb', 'A miss is as good as a mile', 8, 'A M I A G A A M', '{}'::jsonb, null),
('proverb', 'A penny saved is a penny earned', 7, 'A P S I A P E', '{}'::jsonb, null),
('proverb', 'A rolling stone gathers no moss', 6, 'A R S G N M', '{}'::jsonb, null),
('proverb', 'A stitch in time saves nine', 6, 'A S I T S N', '{}'::jsonb, null),
('proverb', 'A watched pot never boils', 5, 'A W P N B', '{}'::jsonb, null),
('proverb', 'Absence makes the heart grow fonder', 6, 'A M T H G F', '{}'::jsonb, null),
('proverb', 'Actions speak louder than words', 5, 'A S L T W', '{}'::jsonb, null),
('proverb', 'All good things must come to an end', 8, 'A G T M C T A E', '{}'::jsonb, null),
('proverb', 'All is fair in love and war', 7, 'A I F I L A W', '{}'::jsonb, null),
('proverb', 'All that glitters is not gold', 6, 'A T G I N G', '{}'::jsonb, null),
('proverb', 'An apple a day keeps the doctor away', 8, 'A A A D K T D A', '{}'::jsonb, null),
('proverb', 'Any port in a storm', 5, 'A P I A S', '{}'::jsonb, null),
('proverb', 'As you make your bed, so you must lie in it', 11, 'A Y M Y B S Y M L I I', '{}'::jsonb, null),
('proverb', 'As you sow, so shall you reap', 7, 'A Y S S S Y R', '{}'::jsonb, null),
('proverb', 'Barking dogs seldom bite', 4, 'B D S B', '{}'::jsonb, null),
('proverb', 'Beauty is in the eye of the beholder', 8, 'B I I T E O T B', '{}'::jsonb, null),
('proverb', 'Beggars cannot be choosers', 4, 'B C B C', '{}'::jsonb, null),
('proverb', 'Better late than never', 4, 'B L T N', '{}'::jsonb, null),
('proverb', 'Better safe than sorry', 4, 'B S T S', '{}'::jsonb, null),
('proverb', 'Better the devil you know than the devil you don''t', 10, 'B T D Y K T T D Y D', '{}'::jsonb, null),
('proverb', 'Birds of a feather flock together', 6, 'B O A F F T', '{}'::jsonb, null),
('proverb', 'Blood is thicker than water', 5, 'B I T T W', '{}'::jsonb, null),
('proverb', 'Charity begins at home', 4, 'C B A H', '{}'::jsonb, null),
('proverb', 'Cleanliness is next to godliness', 5, 'C I N T G', '{}'::jsonb, null),
('proverb', 'Curiosity killed the cat', 4, 'C K T C', '{}'::jsonb, null),
('proverb', 'Cut your coat according to your cloth', 7, 'C Y C A T Y C', '{}'::jsonb, null),
('proverb', 'Dead men tell no tales', 5, 'D M T N T', '{}'::jsonb, null),
('proverb', 'Desperate times call for desperate measures', 6, 'D T C F D M', '{}'::jsonb, null),
('proverb', 'Discretion is the better part of valour', 7, 'D I T B P O V', '{}'::jsonb, null),
('proverb', 'Do not bite the hand that feeds you', 8, 'D N B T H T F Y', '{}'::jsonb, null),
('proverb', 'Do not count your chickens before they hatch', 8, 'D N C Y C B T H', '{}'::jsonb, null),
('proverb', 'Do not cross the bridge until you come to it', 10, 'D N C T B U Y C T I', '{}'::jsonb, null),
('proverb', 'Do not judge a book by its cover', 8, 'D N J A B B I C', '{}'::jsonb, null),
('proverb', 'Do not put all your eggs in one basket', 9, 'D N P A Y E I O B', '{}'::jsonb, null),
('proverb', 'Do unto others as you would have them do unto you', 11, 'D U O A Y W H T D U Y', '{}'::jsonb, null),
('proverb', 'Easier said than done', 4, 'E S T D', '{}'::jsonb, null),
('proverb', 'Easy come, easy go', 4, 'E C E G', '{}'::jsonb, null),
('proverb', 'Empty vessels make the most noise', 6, 'E V M T M N', '{}'::jsonb, null),
('proverb', 'Every cloud has a silver lining', 6, 'E C H A S L', '{}'::jsonb, null),
('proverb', 'Every dog has its day', 5, 'E D H I D', '{}'::jsonb, null),
('proverb', 'Every man has his price', 5, 'E M H H P', '{}'::jsonb, null),
('proverb', 'Every rose has its thorn', 5, 'E R H I T', '{}'::jsonb, null),
('proverb', 'Experience is the best teacher', 5, 'E I T B T', '{}'::jsonb, null),
('proverb', 'Fine feathers make fine birds', 5, 'F F M F B', '{}'::jsonb, null),
('proverb', 'First come, first served', 4, 'F C F S', '{}'::jsonb, null),
('proverb', 'Fortune favours the bold', 4, 'F F T B', '{}'::jsonb, null),
('proverb', 'Good things come to those who wait', 7, 'G T C T T W W', '{}'::jsonb, null),
('proverb', 'Great minds think alike', 4, 'G M T A', '{}'::jsonb, null),
('proverb', 'Half a loaf is better than none', 7, 'H A L I B T N', '{}'::jsonb, null),
('proverb', 'He laughs best who laughs last', 6, 'H L B W L L', '{}'::jsonb, null),
('proverb', 'He who hesitates is lost', 5, 'H W H I L', '{}'::jsonb, null),
('proverb', 'He who lives by the sword shall die by the sword', 11, 'H W L B T S S D B T S', '{}'::jsonb, null),
('proverb', 'Honesty is the best policy', 5, 'H I T B P', '{}'::jsonb, null),
('proverb', 'Hope for the best, prepare for the worst', 8, 'H F T B P F T W', '{}'::jsonb, null),
('proverb', 'If it ain''t broke, don''t fix it', 7, 'I I A B D F I', '{}'::jsonb, null),
('proverb', 'If the shoe fits, wear it', 6, 'I T S F W I', '{}'::jsonb, null),
('proverb', 'It is never too late to learn', 7, 'I I N T L T L', '{}'::jsonb, null),
('proverb', 'It never rains but it pours', 6, 'I N R B I P', '{}'::jsonb, null),
('proverb', 'Keep your friends close and your enemies closer', 8, 'K Y F C A Y E C', '{}'::jsonb, null),
('proverb', 'Laughter is the best medicine', 5, 'L I T B M', '{}'::jsonb, null),
('proverb', 'Let bygones be bygones', 4, 'L B B B', '{}'::jsonb, null),
('proverb', 'Let sleeping dogs lie', 4, 'L S D L', '{}'::jsonb, null),
('proverb', 'Life begins at forty', 4, 'L B A F', '{}'::jsonb, null),
('proverb', 'Life is not all beer and skittles', 7, 'L I N A B A S', '{}'::jsonb, null),
('proverb', 'Live and let live', 4, 'L A L L', '{}'::jsonb, null),
('proverb', 'Look before you leap', 4, 'L B Y L', '{}'::jsonb, null),
('proverb', 'Make hay while the sun shines', 6, 'M H W T S S', '{}'::jsonb, null),
('proverb', 'Many hands make light work', 5, 'M H M L W', '{}'::jsonb, null),
('proverb', 'Money does not grow on trees', 6, 'M D N G O T', '{}'::jsonb, null),
('proverb', 'Necessity is the mother of invention', 6, 'N I T M O I', '{}'::jsonb, null),
('proverb', 'Never judge a book by its cover', 7, 'N J A B B I C', '{}'::jsonb, null),
('proverb', 'Never look a gift horse in the mouth', 8, 'N L A G H I T M', '{}'::jsonb, null),
('proverb', 'Never put off until tomorrow what you can do today', 10, 'N P O U T W Y C D T', '{}'::jsonb, null),
('proverb', 'No news is good news', 5, 'N N I G N', '{}'::jsonb, null),
('proverb', 'No pain, no gain', 4, 'N P N G', '{}'::jsonb, null),
('proverb', 'Nothing ventured, nothing gained', 4, 'N V N G', '{}'::jsonb, null),
('proverb', 'Old habits die hard', 4, 'O H D H', '{}'::jsonb, null),
('proverb', 'Once bitten, twice shy', 4, 'O B T S', '{}'::jsonb, null),
('proverb', 'One good turn deserves another', 5, 'O G T D A', '{}'::jsonb, null),
('proverb', 'One man''s meat is another man''s poison', 7, 'O M M I A M P', '{}'::jsonb, null),
('proverb', 'Opportunity seldom knocks twice', 4, 'O S K T', '{}'::jsonb, null),
('proverb', 'Out of sight, out of mind', 6, 'O O S O O M', '{}'::jsonb, null),
('proverb', 'Patience is a virtue', 4, 'P I A V', '{}'::jsonb, null),
('proverb', 'Penny wise and pound foolish', 5, 'P W A P F', '{}'::jsonb, null),
('proverb', 'Practice makes perfect', 3, 'P M P', '{}'::jsonb, null),
('proverb', 'Prevention is better than cure', 5, 'P I B T C', '{}'::jsonb, null),
('proverb', 'Pride comes before a fall', 5, 'P C B A F', '{}'::jsonb, null),
('proverb', 'Rome was not built in a day', 7, 'R W N B I A D', '{}'::jsonb, null),
('proverb', 'Slow and steady wins the race', 6, 'S A S W T R', '{}'::jsonb, null),
('proverb', 'Spare the rod and spoil the child', 7, 'S T R A S T C', '{}'::jsonb, null),
('proverb', 'Still waters run deep', 4, 'S W R D', '{}'::jsonb, null),
('proverb', 'Strike while the iron is hot', 6, 'S W T I I H', '{}'::jsonb, null),
('proverb', 'Take care of the pennies and the pounds will take care of themselves', 13, 'T C O T P A T P W T C O T', '{}'::jsonb, null),
('proverb', 'The best defence is a good offence', 7, 'T B D I A G O', '{}'::jsonb, null),
('proverb', 'The bigger they are, the harder they fall', 8, 'T B T A T H T F', '{}'::jsonb, null),
('proverb', 'The customer is always right', 5, 'T C I A R', '{}'::jsonb, null),
('proverb', 'The early bird catches the worm', 6, 'T E B C T W', '{}'::jsonb, null),
('proverb', 'The end justifies the means', 5, 'T E J T M', '{}'::jsonb, null),
('proverb', 'The exception proves the rule', 5, 'T E P T R', '{}'::jsonb, null),
('proverb', 'The grass is always greener on the other side', 9, 'T G I A G O T O S', '{}'::jsonb, null),
('proverb', 'The pen is mightier than the sword', 7, 'T P I M T T S', '{}'::jsonb, null),
('proverb', 'The proof of the pudding is in the eating', 9, 'T P O T P I I T E', '{}'::jsonb, null),
('proverb', 'The road to hell is paved with good intentions', 9, 'T R T H I P W G I', '{}'::jsonb, null),
('proverb', 'There are none so blind as those who will not see', 11, 'T A N S B A T W W N S', '{}'::jsonb, null),
('proverb', 'There is honour among thieves', 5, 'T I H A T', '{}'::jsonb, null),
('proverb', 'There is more than one way to skin a cat', 10, 'T I M T O W T S A C', '{}'::jsonb, null),
('proverb', 'There is no place like home', 6, 'T I N P L H', '{}'::jsonb, null),
('proverb', 'There is no smoke without fire', 6, 'T I N S W F', '{}'::jsonb, null),
('proverb', 'Time and tide wait for no man', 7, 'T A T W F N M', '{}'::jsonb, null),
('proverb', 'Time heals all wounds', 4, 'T H A W', '{}'::jsonb, null),
('proverb', 'To err is human, to forgive divine', 7, 'T E I H T F D', '{}'::jsonb, null),
('proverb', 'Too many cooks spoil the broth', 6, 'T M C S T B', '{}'::jsonb, null),
('proverb', 'Truth is stranger than fiction', 5, 'T I S T F', '{}'::jsonb, null),
('proverb', 'Two heads are better than one', 6, 'T H A B T O', '{}'::jsonb, null),
('proverb', 'United we stand, divided we fall', 6, 'U W S D W F', '{}'::jsonb, null),
('proverb', 'Variety is the spice of life', 6, 'V I T S O L', '{}'::jsonb, null),
('proverb', 'Waste not, want not', 4, 'W N W N', '{}'::jsonb, null),
('proverb', 'Well begun is half done', 5, 'W B I H D', '{}'::jsonb, null),
('proverb', 'What goes around comes around', 5, 'W G A C A', '{}'::jsonb, null),
('proverb', 'What you lose on the swings you gain on the roundabouts', 11, 'W Y L O T S Y G O T R', '{}'::jsonb, null),
('proverb', 'When in Rome, do as the Romans do', 8, 'W I R D A T R D', '{}'::jsonb, null),
('proverb', 'Where there is a will, there is a way', 9, 'W T I A W T I A W', '{}'::jsonb, null),
('proverb', 'Where there is smoke, there is fire', 7, 'W T I S T I F', '{}'::jsonb, null),
('proverb', 'You are what you eat', 5, 'Y A W Y E', '{}'::jsonb, null),
('proverb', 'You can lead a horse to water, but you cannot make it drink', 13, 'Y C L A H T W B Y C M I D', '{}'::jsonb, null),
('proverb', 'You cannot have your cake and eat it too', 9, 'Y C H Y C A E I T', '{}'::jsonb, null),
('proverb', 'You cannot make an omelette without breaking eggs', 8, 'Y C M A O W B E', '{}'::jsonb, null),
('proverb', 'You cannot teach an old dog new tricks', 8, 'Y C T A O D N T', '{}'::jsonb, null),
('proverb', 'You reap what you sow', 5, 'Y R W Y S', '{}'::jsonb, null),
('proverb', 'Youth is wasted on the young', 6, 'Y I W O T Y', '{}'::jsonb, null),
('proverb', 'Necessity knows no law', 4, 'N K N L', '{}'::jsonb, null),
('proverb', 'The squeaky wheel gets the grease', 6, 'T S W G T G', '{}'::jsonb, null),
('song', 'Smells Like Teen Spirit', 4, 'S L T S', '{"artist": "Nirvana"}'::jsonb, null),
('song', 'A Change Is Gonna Come', 5, 'A C I G C', '{"artist": "Sam Cooke"}'::jsonb, null),
('song', 'Blowin'' in the Wind', 4, 'B I T W', '{"artist": "Bob Dylan"}'::jsonb, null),
('song', 'I Want to Hold Your Hand', 6, 'I W T H Y H', '{"artist": "The Beatles"}'::jsonb, null),
('song', 'A Day in the Life', 5, 'A D I T L', '{"artist": "The Beatles"}'::jsonb, null),
('song', 'I Walk the Line', 4, 'I W T L', '{"artist": "Johnny Cash"}'::jsonb, null),
('song', 'Sympathy for the Devil', 4, 'S F T D', '{"artist": "The Rolling Stones"}'::jsonb, null),
('song', 'You''ve Lost That Lovin'' Feelin''', 5, 'Y L T L F', '{"artist": "The Righteous Brothers"}'::jsonb, null),
('song', 'No Woman, No Cry', 4, 'N W N C', '{"artist": "Bob Marley & The Wailers"}'::jsonb, null),
('song', 'That''ll Be the Day', 4, 'T B T D', '{"artist": "Buddy Holly & The Crickets"}'::jsonb, null),
('song', 'Dancing in the Street', 4, 'D I T S', '{"artist": "Martha & The Vandellas"}'::jsonb, null),
('song', 'Georgia on My Mind', 4, 'G O M M', '{"artist": "Ray Charles"}'::jsonb, null),
('song', 'Bridge Over Troubled Water', 4, 'B O T W', '{"artist": "Simon & Garfunkel"}'::jsonb, null),
('song', 'All Along the Watchtower', 4, 'A A T W', '{"artist": "Jimi Hendrix"}'::jsonb, null),
('song', 'Papa''s Got A Brand New Bag', 6, 'P G A B N B', '{"artist": "James Brown"}'::jsonb, null),
('song', 'I Heard It Through The Grapevine', 6, 'I H I T T G', '{"artist": "Marvin Gaye"}'::jsonb, null),
('song', 'I Still Haven''t Found What I''m Looking For', 8, 'I S H F W I L F', '{"artist": "U2"}'::jsonb, null),
('song', 'Good Golly Miss Molly', 4, 'G G M M', '{"artist": "Little Richard"}'::jsonb, null),
('song', 'I''m So Lonesome I Could Cry', 6, 'I S L I C C', '{"artist": "Hank Williams"}'::jsonb, null),
('song', 'Up On the Roof', 4, 'U O T R', '{"artist": "The Drifters"}'::jsonb, null),
('song', 'Da Doo Ron Ron', 4, 'D D R R', '{"artist": "The Crystals"}'::jsonb, null),
('song', 'Take Me to the River', 5, 'T M T T R', '{"artist": "Al Green"}'::jsonb, null),
('song', 'Go Your Own Way', 4, 'G Y O W', '{"artist": "Fleetwood Mac"}'::jsonb, null),
('song', 'I Want You Back', 4, 'I W Y B', '{"artist": "The Jackson 5"}'::jsonb, null),
('song', 'The House Of The Rising Sun', 6, 'T H O T R S', '{"artist": "The Animals"}'::jsonb, null),
('song', 'It''s A Man''s Man''s Man''s World', 6, 'I A M M M W', '{"artist": "James Brown"}'::jsonb, null),
('song', 'Will You Love Me Tomorrow', 5, 'W Y L M T', '{"artist": "The Shirelles"}'::jsonb, null),
('song', 'Shake, Rattle And Roll', 4, 'S R A R', '{"artist": "Big Joe Turner"}'::jsonb, null),
('song', 'Rock And Roll Music', 4, 'R A R M', '{"artist": "Chuck Berry"}'::jsonb, null),
('song', 'Born To Be Wild', 4, 'B T B W', '{"artist": "Steppenwolf"}'::jsonb, null),
('song', 'With Or Without You', 4, 'W O W Y', '{"artist": "U2"}'::jsonb, null),
('song', 'Who Do You Love', 4, 'W D Y L', '{"artist": "Bo Diddley"}'::jsonb, null),
('song', 'Won''t Get Fooled Again', 4, 'W G F A', '{"artist": "The Who"}'::jsonb, null),
('song', 'In The Midnight Hour', 4, 'I T M H', '{"artist": "Wilson Pickett"}'::jsonb, null),
('song', 'While My Guitar Gently Weeps', 5, 'W M G G W', '{"artist": "The Beatles"}'::jsonb, null),
('song', 'Where Is My Mind?', 4, 'W I M M', '{"artist": "Pixies"}'::jsonb, null),
('song', 'Welcome to the Jungle', 4, 'W T T J', '{"artist": "Guns N'' Roses"}'::jsonb, null),
('song', 'Cranes in the Sky', 4, 'C I T S', '{"artist": "Solange"}'::jsonb, null),
('song', 'I Can''t Help Myself', 4, 'I C H M', '{"artist": "Four Tops"}'::jsonb, null),
('song', 'Back That Azz Up', 4, 'B T A U', '{"artist": "Juvenile"}'::jsonb, null),
('song', 'Our Lips Are Sealed', 4, 'O L A S', '{"artist": "The Go-Go''s"}'::jsonb, null),
('song', 'Sunday Morning Coming Down', 4, 'S M C D', '{"artist": "Kris Kristofferson"}'::jsonb, null),
('song', 'Midnight Train to Georgia', 4, 'M T T G', '{"artist": "Gladys Knight and the Pips"}'::jsonb, null),
('song', 'Sweet Child O'' Mine', 4, 'S C O M', '{"artist": "Guns N'' Roses"}'::jsonb, null),
('song', 'I Wanna Be Your Dog', 5, 'I W B Y D', '{"artist": "The Stooges"}'::jsonb, null),
('song', 'The Tracks of My Tears', 5, 'T T O M T', '{"artist": "Smokey Robinson"}'::jsonb, null),
('song', 'Signed, Sealed, Delivered I''m Yours', 5, 'S S D I Y', '{"artist": "Stevie Wonder"}'::jsonb, null),
('song', 'I Just Don''t Know What to Do with Myself', 9, 'I J D K W T D W M', '{"artist": "The White Stripes"}'::jsonb, null),
('song', 'Anarchy in the U.K.', 4, 'A I T U', '{"artist": "Sex Pistols"}'::jsonb, null),
('song', 'I Want to Break Free', 5, 'I W T B F', '{"artist": "Queen"}'::jsonb, null),
('song', 'Once in a Lifetime', 4, 'O I A L', '{"artist": "Talking Heads"}'::jsonb, null),
('song', 'Single Ladies (Put a Ring on It)', 7, 'S L P A R O I', '{"artist": "Beyoncé"}'::jsonb, null),
('song', 'The Boys of Summer', 4, 'T B O S', '{"artist": "Don Henley"}'::jsonb, null),
('song', 'All the Small Things', 4, 'A T S T', '{"artist": "Blink-182"}'::jsonb, null),
('song', 'Piece of My Heart', 4, 'P O M H', '{"artist": "Big Brother and the Holding Company"}'::jsonb, null),
('song', 'Keep On Loving You', 4, 'K O L Y', '{"artist": "REO Speedwagon"}'::jsonb, null),
('song', 'I Shot the Sheriff', 4, 'I S T S', '{"artist": "Bob Marley"}'::jsonb, null),
('song', 'The Boy Is Mine', 4, 'T B I M', '{"artist": "Brandy & Monica"}'::jsonb, null),
('song', 'I Write the Songs', 4, 'I W T S', '{"artist": "Barry Manilow"}'::jsonb, null),
('song', 'You Shook Me All Night Long', 6, 'Y S M A N L', '{"artist": "AC/DC"}'::jsonb, null),
('song', 'Another Brick in the Wall', 5, 'A B I T W', '{"artist": "Pink Floyd"}'::jsonb, null),
('song', 'Come As You Are', 4, 'C A Y A', '{"artist": "Nirvana"}'::jsonb, null),
('song', 'One Way or Another', 4, 'O W O A', '{"artist": "Blondie"}'::jsonb, null),
('song', 'Wake Me Up Before You Go-Go', 6, 'W M U B Y G', '{"artist": "Wham!"}'::jsonb, null),
('song', 'Don''t You Want Me', 4, 'D Y W M', '{"artist": "The Human League"}'::jsonb, null),
('song', 'Livin'' on a Prayer', 4, 'L O A P', '{"artist": "Bon Jovi"}'::jsonb, null),
('song', 'Love Will Tear Us Apart', 5, 'L W T U A', '{"artist": "Joy Division"}'::jsonb, null),
('song', 'Fight for Your Right', 4, 'F F Y R', '{"artist": "Beastie Boys"}'::jsonb, null),
('song', 'Wind Beneath My Wings', 4, 'W B M W', '{"artist": "Bette Midler"}'::jsonb, null),
('song', 'Man in the Mirror', 4, 'M I T M', '{"artist": "Michael Jackson"}'::jsonb, null),
('song', 'Killing in the Name', 4, 'K I T N', '{"artist": "Rage Against the Machine"}'::jsonb, null),
('song', 'Mama Said Knock You Out', 5, 'M S K Y O', '{"artist": "LL Cool J"}'::jsonb, null),
('song', 'You Can''t Always Get What You Want', 7, 'Y C A G W Y W', '{"artist": "The Rolling Stones"}'::jsonb, null),
('song', 'Waiting on a Friend', 4, 'W O A F', '{"artist": "The Rolling Stones"}'::jsonb, null),
('song', 'Tired of Being Alone', 4, 'T O B A', '{"artist": "Al Green"}'::jsonb, null),
('song', 'Papa Was a Rollin'' Stone', 5, 'P W A R S', '{"artist": "The Temptations"}'::jsonb, null),
('song', 'Ain''t No Mountain High Enough', 5, 'A N M H E', '{"artist": "Marvin Gaye & Tammi Terrell"}'::jsonb, null),
('song', 'What a Wonderful World', 4, 'W A W W', '{"artist": "Louis Armstrong"}'::jsonb, null),
('song', 'Stand By Your Man', 4, 'S B Y M', '{"artist": "Tammy Wynette"}'::jsonb, null),
('song', 'In the Still of the Night', 6, 'I T S O T N', '{"artist": "The Five Satins"}'::jsonb, null),
('song', 'I Got You (I Feel Good)', 6, 'I G Y I F G', '{"artist": "James Brown"}'::jsonb, null),
('song', 'Living for the City', 4, 'L F T C', '{"artist": "Stevie Wonder"}'::jsonb, null),
('song', 'Don''t Let Me Down', 4, 'D L M D', '{"artist": "The Beatles"}'::jsonb, null),
('song', 'I Can''t Make You Love Me', 6, 'I C M Y L M', '{"artist": "Bonnie Raitt"}'::jsonb, null),
('song', 'Let''s Get It On', 4, 'L G I O', '{"artist": "Marvin Gaye"}'::jsonb, null),
('song', 'We Are the Champions', 4, 'W A T C', '{"artist": "Queen"}'::jsonb, null),
('song', 'Every Breath You Take', 4, 'E B Y T', '{"artist": "The Police"}'::jsonb, null),
('song', 'Baby One More Time', 4, 'B O M T', '{"artist": "Britney Spears"}'::jsonb, null),
('song', 'Pour Some Sugar on Me', 5, 'P S S O M', '{"artist": "Def Leppard"}'::jsonb, null),
('song', 'I Love Rock ''n'' Roll', 5, 'I L R N R', '{"artist": "Joan Jett & the Blackhearts"}'::jsonb, null),
('song', 'Don''t You (Forget About Me)', 5, 'D Y F A M', '{"artist": "Simple Minds"}'::jsonb, null),
('song', 'I Wanna Dance with Somebody', 5, 'I W D W S', '{"artist": "Whitney Houston"}'::jsonb, null),
('song', 'Walk on the Wild Side', 5, 'W O T W S', '{"artist": "Lou Reed"}'::jsonb, null),
('song', 'You Really Got Me', 4, 'Y R G M', '{"artist": "The Kinks"}'::jsonb, null),
('song', 'The Sound of Silence', 4, 'T S O S', '{"artist": "Simon & Garfunkel"}'::jsonb, null),
('song', 'Don''t Stop ''Til You Get Enough', 6, 'D S T Y G E', '{"artist": "Michael Jackson"}'::jsonb, null),
('song', 'Should I Stay or Should I Go', 7, 'S I S O S I G', '{"artist": "The Clash"}'::jsonb, null),
('song', 'Here Comes the Sun', 4, 'H C T S', '{"artist": "The Beatles"}'::jsonb, null),
('song', 'All You Need Is Love', 5, 'A Y N I L', '{"artist": "The Beatles"}'::jsonb, null),
('song', 'Dancing in the Dark', 4, 'D I T D', '{"artist": "Bruce Springsteen"}'::jsonb, null),
('song', 'We Didn''t Start the Fire', 5, 'W D S T F', '{"artist": "Billy Joel"}'::jsonb, null),
('song', 'I Put a Spell on You', 6, 'I P A S O Y', '{"artist": "Screamin'' Jay Hawkins"}'::jsonb, null),
('song', 'You Give Love a Bad Name', 6, 'Y G L A B N', '{"artist": "Bon Jovi"}'::jsonb, null),
('song', 'God Save the Queen', 4, 'G S T Q', '{"artist": "Sex Pistols"}'::jsonb, null),
('song', '(You Make Me Feel Like) A Natural Woman', 8, 'Y M M F L A N W', '{"artist": "Aretha Franklin"}'::jsonb, null),
('song', 'Me and Bobby McGee', 4, 'M A B M', '{"artist": "Janis Joplin"}'::jsonb, null),
('song', 'The Times They Are A-Changin''', 5, 'T T T A A', '{"artist": "Bob Dylan"}'::jsonb, null),
('song', 'You Are the Sunshine of My Life', 7, 'Y A T S O M L', '{"artist": "Stevie Wonder"}'::jsonb, null),
('song', 'Do You Believe in Magic', 5, 'D Y B I M', '{"artist": "The Lovin'' Spoonful"}'::jsonb, null),
('song', 'I Can See for Miles', 5, 'I C S F M', '{"artist": "The Who"}'::jsonb, null),
('song', 'A Whiter Shade of Pale', 5, 'A W S O P', '{"artist": "Procol Harum"}'::jsonb, null),
('song', 'For What It''s Worth', 4, 'F W I W', '{"artist": "Buffalo Springfield"}'::jsonb, null),
('song', 'I Fought the Law', 4, 'I F T L', '{"artist": "The Bobby Fuller Four"}'::jsonb, null),
('song', 'The Girl from Ipanema', 4, 'T G F I', '{"artist": "Stan Getz & João Gilberto"}'::jsonb, null),
('song', 'Crying in the Chapel', 4, 'C I T C', '{"artist": "Elvis Presley"}'::jsonb, null),
('song', 'I Only Have Eyes for You', 6, 'I O H E F Y', '{"artist": "The Flamingos"}'::jsonb, null),
('song', 'Why Do Fools Fall in Love', 6, 'W D F F I L', '{"artist": "Frankie Lymon & The Teenagers"}'::jsonb, null),
('song', 'Great Balls of Fire', 4, 'G B O F', '{"artist": "Jerry Lee Lewis"}'::jsonb, null),
('song', 'Earth Angel (Will You Be Mine)', 6, 'E A W Y B M', '{"artist": "The Penguins"}'::jsonb, null),
('song', 'Ain''t It a Shame', 4, 'A I A S', '{"artist": "Fats Domino"}'::jsonb, null),
('song', 'I''m Your Hoochie Coochie Man', 5, 'I Y H C M', '{"artist": "Muddy Waters"}'::jsonb, null),
('song', 'Good Times Bad Times', 4, 'G T B T', '{"artist": "Led Zeppelin"}'::jsonb, null),
('song', 'The Dark End of the Street', 6, 'T D E O T S', '{"artist": "James Carr"}'::jsonb, null),
('song', 'Hold On, I''m Comin''', 4, 'H O I C', '{"artist": "Sam & Dave"}'::jsonb, null),
('song', 'Just My Imagination (Running Away with Me)', 7, 'J M I R A W M', '{"artist": "The Temptations"}'::jsonb, null),
('song', 'I Can''t Quit You Baby', 5, 'I C Q Y B', '{"artist": "Otis Rush"}'::jsonb, null),
('song', 'Baby I Need Your Loving', 5, 'B I N Y L', '{"artist": "Four Tops"}'::jsonb, null),
('song', 'Reach Out I''ll Be There', 5, 'R O I B T', '{"artist": "Four Tops"}'::jsonb, null),
('song', 'Stop! In the Name of Love', 6, 'S I T N O L', '{"artist": "The Supremes"}'::jsonb, null),
('song', 'You Keep Me Hangin'' On', 5, 'Y K M H O', '{"artist": "The Supremes"}'::jsonb, null),
('song', 'Say It Loud - I''m Black and I''m Proud', 9, 'S I L I B A I P', '{"artist": "James Brown"}'::jsonb, null),
('song', 'What''s Love Got to Do with It', 7, 'W L G T D W I', '{"artist": "Tina Turner"}'::jsonb, null),
('song', 'Thank You (Falettinme Be Mice Elf Agin)', 7, 'T Y F B M E A', '{"artist": "Sly & the Family Stone"}'::jsonb, null),
('song', 'Dance to the Music', 4, 'D T T M', '{"artist": "Sly & the Family Stone"}'::jsonb, null),
('song', 'I''ll Take You There', 4, 'I T Y T', '{"artist": "The Staple Singers"}'::jsonb, null),
('song', 'If You Don''t Know Me by Now', 7, 'I Y D K M B N', '{"artist": "Harold Melvin & The Blue Notes"}'::jsonb, null),
('song', 'Best of My Love', 4, 'B O M L', '{"artist": "The Emotions"}'::jsonb, null),
('song', 'Take Me Home, Country Roads', 5, 'T M H C R', '{"artist": "John Denver"}'::jsonb, null),
('song', 'Can''t Buy Me Love', 4, 'C B M L', '{"artist": "The Beatles"}'::jsonb, null),
('song', 'Lucy in the Sky with Diamonds', 6, 'L I T S W D', '{"artist": "The Beatles"}'::jsonb, null),
('song', 'I Saw Her Standing There', 5, 'I S H S T', '{"artist": "The Beatles"}'::jsonb, null),
('song', 'Got to Get You into My Life', 7, 'G T G Y I M L', '{"artist": "The Beatles"}'::jsonb, null),
('song', 'The Long and Winding Road', 5, 'T L A W R', '{"artist": "The Beatles"}'::jsonb, null),
('song', 'Have You Ever Seen the Rain', 6, 'H Y E S T R', '{"artist": "Creedence Clearwater Revival"}'::jsonb, null),
('song', 'Who''ll Stop the Rain', 4, 'W S T R', '{"artist": "Creedence Clearwater Revival"}'::jsonb, null),
('song', 'Lookin'' Out My Back Door', 5, 'L O M B D', '{"artist": "Creedence Clearwater Revival"}'::jsonb, null),
('book', 'One Hundred Years of Solitude', 5, 'O H Y O S', '{"author": "Gabriel García Márquez"}'::jsonb, null),
('book', 'The Curious Incident of the Dog in the Night-Time', 9, 'T C I O T D I T N', '{"author": "Mark Haddon"}'::jsonb, null),
('book', 'The Fault in Our Stars', 5, 'T F I O S', '{"author": "John Green"}'::jsonb, null),
('book', 'The Perks of Being a Wallflower', 6, 'T P O B A W', '{"author": "Stephen Chbosky"}'::jsonb, null),
('book', 'The Shadow of the Wind', 5, 'T S O T W', '{"author": "Carlos Ruiz Zafón"}'::jsonb, null),
('book', 'The Name of the Rose', 5, 'T N O T R', '{"author": "Umberto Eco"}'::jsonb, null),
('book', 'The Amazing Adventures of Kavalier & Clay', 7, 'T A A O K C', '{"author": "Michael Chabon"}'::jsonb, null),
('book', 'The Brief Wondrous Life of Oscar Wao', 7, 'T B W L O O W', '{"author": "Junot Díaz"}'::jsonb, null),
('book', 'Love in the Time of Cholera', 6, 'L I T T O C', '{"author": "Gabriel García Márquez"}'::jsonb, null),
('book', 'Chronicle of a Death Foretold', 5, 'C O A D F', '{"author": "Gabriel García Márquez"}'::jsonb, null),
('book', 'A Tale of Two Cities', 5, 'A T O T C', '{"author": "Charles Dickens"}'::jsonb, null),
('book', 'A Study in Scarlet', 4, 'A S I S', '{"author": "Arthur Conan Doyle"}'::jsonb, null),
('book', 'A Portrait of the Artist as a Young Man', 9, 'A P O T A A A Y M', '{"author": "James Joyce"}'::jsonb, null),
('book', 'A Heartbreaking Work of Staggering Genius', 6, 'A H W O S G', '{"author": "Dave Eggers"}'::jsonb, null),
('book', 'A Confederacy of Dunces', 4, 'A C O D', '{"author": "John Kennedy Toole"}'::jsonb, null),
('book', 'A Prayer for Owen Meany', 5, 'A P F O M', '{"author": "John Irving"}'::jsonb, null),
('book', 'A River Runs Through It', 5, 'A R R T I', '{"author": "Norman Maclean"}'::jsonb, null),
('book', 'All Quiet on the Western Front', 6, 'A Q O T W F', '{"author": "Erich Maria Remarque"}'::jsonb, null),
('book', 'All the King''s Men', 4, 'A T K M', '{"author": "Robert Penn Warren"}'::jsonb, null),
('book', 'Anne of Green Gables', 4, 'A O G G', '{"author": "L. M. Montgomery"}'::jsonb, null),
('book', 'Are You There God? It''s Me, Margaret.', 7, 'A Y T G I M M', '{"author": "Judy Blume"}'::jsonb, null),
('book', 'Cloudy with a Chance of Meatballs', 6, 'C W A C O M', '{"author": "Judi Barrett"}'::jsonb, null),
('book', 'Fried Green Tomatoes at the Whistle Stop Cafe', 8, 'F G T A T W S C', '{"author": "Fannie Flagg"}'::jsonb, null),
('book', 'From Here to Eternity', 4, 'F H T E', '{"author": "James Jones"}'::jsonb, null),
('book', 'Gone with the Wind', 4, 'G W T W', '{"author": "Margaret Mitchell"}'::jsonb, null),
('book', 'Green Eggs and Ham', 4, 'G E A H', '{"author": "Dr. Seuss"}'::jsonb, null),
('book', 'Gulliver''s Travels into Several Remote Nations of the World', 9, 'G T I S R N O T W', '{"author": "Jonathan Swift"}'::jsonb, null),
('book', 'I Know Why the Caged Bird Sings', 7, 'I K W T C B S', '{"author": "Maya Angelou"}'::jsonb, null),
('book', 'In the Heart of the Sea', 6, 'I T H O T S', '{"author": "Nathaniel Philbrick"}'::jsonb, null),
('book', 'Journey to the Center of the Earth', 7, 'J T T C O T E', '{"author": "Jules Verne"}'::jsonb, null),
('book', 'Journey to the End of the Night', 7, 'J T T E O T N', '{"author": "Louis-Ferdinand Céline"}'::jsonb, null),
('book', 'Midnight in the Garden of Good and Evil', 8, 'M I T G O G A E', '{"author": "John Berendt"}'::jsonb, null),
('book', 'My Side of the Mountain', 5, 'M S O T M', '{"author": "Jean Craighead George"}'::jsonb, null),
('book', 'Of Mice and Men', 4, 'O M A M', '{"author": "John Steinbeck"}'::jsonb, null),
('book', 'Pride and Prejudice and Zombies', 5, 'P A P A Z', '{"author": "Seth Grahame-Smith"}'::jsonb, null),
('book', 'Stranger in a Strange Land', 5, 'S I A S L', '{"author": "Robert A. Heinlein"}'::jsonb, null),
('book', 'The Art of War', 4, 'T A O W', '{"author": "Sun Tzu"}'::jsonb, null),
('book', 'The Grapes of Wrath', 4, 'T G O W', '{"author": "John Steinbeck"}'::jsonb, null),
('book', 'The Old Man and the Sea', 6, 'T O M A T S', '{"author": "Ernest Hemingway"}'::jsonb, null),
('book', 'The Picture of Dorian Gray', 5, 'T P O D G', '{"author": "Oscar Wilde"}'::jsonb, null),
('book', 'The Count of Monte Cristo', 5, 'T C O M C', '{"author": "Alexandre Dumas"}'::jsonb, null),
('book', 'The Hunchback of Notre-Dame', 4, 'T H O N', '{"author": "Victor Hugo"}'::jsonb, null),
('book', 'The House of the Spirits', 5, 'T H O T S', '{"author": "Isabel Allende"}'::jsonb, null),
('book', 'The Wind-Up Bird Chronicle', 4, 'T W B C', '{"author": "Haruki Murakami"}'::jsonb, null),
('book', 'The Da Vinci Code', 4, 'T D V C', '{"author": "Dan Brown"}'::jsonb, null),
('book', 'The Devil Wears Prada', 4, 'T D W P', '{"author": "Lauren Weisberger"}'::jsonb, null),
('book', 'The Five People You Meet in Heaven', 7, 'T F P Y M I H', '{"author": "Mitch Albom"}'::jsonb, null),
('book', 'The Seven Husbands of Evelyn Hugo', 6, 'T S H O E H', '{"author": "Taylor Jenkins Reid"}'::jsonb, null),
('book', 'The Boy in the Striped Pyjamas', 6, 'T B I T S P', '{"author": "John Boyne"}'::jsonb, null),
('book', 'The Curious Case of Benjamin Button', 6, 'T C C O B B', '{"author": "F. Scott Fitzgerald"}'::jsonb, null),
('book', 'The Girl on the Train', 5, 'T G O T T', '{"author": "Paula Hawkins"}'::jsonb, null),
('book', 'The Road Less Traveled', 4, 'T R L T', '{"author": "M. Scott Peck"}'::jsonb, null),
('book', 'The Millionaire Next Door', 4, 'T M N D', '{"author": "Thomas J. Stanley & William D. Danko"}'::jsonb, null),
('book', 'The Warmth of Other Suns', 5, 'T W O O S', '{"author": "Isabel Wilkerson"}'::jsonb, null),
('book', 'The Immortal Life of Henrietta Lacks', 6, 'T I L O H L', '{"author": "Rebecca Skloot"}'::jsonb, null),
('book', 'The Emperor of All Maladies', 5, 'T E O A M', '{"author": "Siddhartha Mukherjee"}'::jsonb, null),
('book', 'The Devil in the White City', 6, 'T D I T W C', '{"author": "Erik Larson"}'::jsonb, null),
('book', 'The Man Who Mistook His Wife for a Hat', 9, 'T M W M H W F A H', '{"author": "Oliver Sacks"}'::jsonb, null),
('book', 'The Heart Is a Lonely Hunter', 6, 'T H I A L H', '{"author": "Carson McCullers"}'::jsonb, null),
('book', 'The Remains of the Day', 5, 'T R O T D', '{"author": "Kazuo Ishiguro"}'::jsonb, null),
('book', 'The Unbearable Lightness of Being', 5, 'T U L O B', '{"author": "Milan Kundera"}'::jsonb, null),
('book', 'The Sound and the Fury', 5, 'T S A T F', '{"author": "William Faulkner"}'::jsonb, null),
('book', 'The Bonfire of the Vanities', 5, 'T B O T V', '{"author": "Tom Wolfe"}'::jsonb, null),
('book', 'The Age of Innocence', 4, 'T A O I', '{"author": "Edith Wharton"}'::jsonb, null),
('book', 'The French Lieutenant''s Woman', 4, 'T F L W', '{"author": "John Fowles"}'::jsonb, null),
('book', 'The God of Small Things', 5, 'T G O S T', '{"author": "Arundhati Roy"}'::jsonb, null),
('book', 'The House on Mango Street', 5, 'T H O M S', '{"author": "Sandra Cisneros"}'::jsonb, null),
('book', 'The Joy Luck Club', 4, 'T J L C', '{"author": "Amy Tan"}'::jsonb, null),
('book', 'The Heart of the Matter', 5, 'T H O T M', '{"author": "Graham Greene"}'::jsonb, null),
('book', 'The Spy Who Came in from the Cold', 8, 'T S W C I F T C', '{"author": "John le Carré"}'::jsonb, null),
('book', 'The Left Hand of Darkness', 5, 'T L H O D', '{"author": "Ursula K. Le Guin"}'::jsonb, null),
('book', 'And Then There Were None', 5, 'A T T W N', '{"author": "Agatha Christie"}'::jsonb, null),
('book', 'We Need to Talk About Kevin', 6, 'W N T T A K', '{"author": "Lionel Shriver"}'::jsonb, null),
('book', 'Where the Crawdads Sing', 4, 'W T C S', '{"author": "Delia Owens"}'::jsonb, null),
('book', 'Where the Red Fern Grows', 5, 'W T R F G', '{"author": "Wilson Rawls"}'::jsonb, null),
('book', 'Where the Sidewalk Ends', 4, 'W T S E', '{"author": "Shel Silverstein"}'::jsonb, null),
('book', 'Who Moved My Cheese?', 4, 'W M M C', '{"author": "Spencer Johnson"}'::jsonb, null),
('book', 'Zen and the Art of Motorcycle Maintenance', 7, 'Z A T A O M M', '{"author": "Robert M. Pirsig"}'::jsonb, null),
('book', 'The Things They Carried', 4, 'T T T C', '{"author": "Tim O''Brien"}'::jsonb, null),
('book', 'The Sun Also Rises', 4, 'T S A R', '{"author": "Ernest Hemingway"}'::jsonb, null),
('book', 'The Silence of the Lambs', 5, 'T S O T L', '{"author": "Thomas Harris"}'::jsonb, null),
('book', 'The Pillars of the Earth', 5, 'T P O T E', '{"author": "Ken Follett"}'::jsonb, null),
('book', 'The Once and Future King', 5, 'T O A F K', '{"author": "T. H. White"}'::jsonb, null),
('book', 'The Last of the Mohicans', 5, 'T L O T M', '{"author": "James Fenimore Cooper"}'::jsonb, null),
('book', 'The Wind in the Willows', 5, 'T W I T W', '{"author": "Kenneth Grahame"}'::jsonb, null),
('book', 'The Tale of Peter Rabbit', 5, 'T T O P R', '{"author": "Beatrix Potter"}'::jsonb, null),
('book', 'The Call of the Wild', 5, 'T C O T W', '{"author": "Jack London"}'::jsonb, null),
('book', 'The Autobiography of Malcolm X', 5, 'T A O M X', '{"author": "Malcolm X & Alex Haley"}'::jsonb, null),
('book', 'Their Eyes Were Watching God', 5, 'T E W W G', '{"author": "Zora Neale Hurston"}'::jsonb, null),
('book', 'Twenty Thousand Leagues Under the Seas', 6, 'T T L U T S', '{"author": "Jules Verne"}'::jsonb, null),
('book', 'The Story of My Life', 5, 'T S O M L', '{"author": "Helen Keller"}'::jsonb, null),
('book', 'The Life of Pi', 4, 'T L O P', '{"author": "Yann Martel"}'::jsonb, null),
('book', 'The World According to Garp', 5, 'T W A T G', '{"author": "John Irving"}'::jsonb, null),
('book', 'The Elegance of the Hedgehog', 5, 'T E O T H', '{"author": "Muriel Barbery"}'::jsonb, null),
('book', 'The Memory Keeper''s Daughter', 4, 'T M K D', '{"author": "Kim Edwards"}'::jsonb, null),
('book', 'The Year of Magical Thinking', 5, 'T Y O M T', '{"author": "Joan Didion"}'::jsonb, null),
('book', 'The Heart of Darkness', 4, 'T H O D', '{"author": "Joseph Conrad"}'::jsonb, null),
('book', 'The No. 1 Ladies'' Detective Agency', 6, 'T N L D A', '{"author": "Alexander McCall Smith"}'::jsonb, null),
('book', 'The Absolutely True Diary of a Part-Time Indian', 8, 'T A T D O A P I', '{"author": "Sherman Alexie"}'::jsonb, null),
('book', 'The Guernsey Literary and Potato Peel Pie Society', 8, 'T G L A P P P S', '{"author": "Mary Ann Shaffer & Annie Barrows"}'::jsonb, null),
('book', 'The 7 Habits of Highly Effective People', 7, 'T H O H E P', '{"author": "Stephen R. Covey"}'::jsonb, null),
('book', 'The Subtle Art of Not Giving a Fck', 8, 'T S A O N G A F', '{"author": "Mark Manson"}'::jsonb, null),
('book', 'The Interpretation of Dreams', 4, 'T I O D', '{"author": "Sigmund Freud"}'::jsonb, null),
('book', 'The Structure of Scientific Revolutions', 5, 'T S O S R', '{"author": "Thomas S. Kuhn"}'::jsonb, null),
('book', 'The Souls of Black Folk', 5, 'T S O B F', '{"author": "W. E. B. Du Bois"}'::jsonb, null),
('book', 'The Origin of Species', 4, 'T O O S', '{"author": "Charles Darwin"}'::jsonb, null),
('book', 'The Wealth of Nations', 4, 'T W O N', '{"author": "Adam Smith"}'::jsonb, null),
('book', 'The Rights of Man', 4, 'T R O M', '{"author": "Thomas Paine"}'::jsonb, null),
('book', 'The Communist Manifesto', 3, 'T C M', '{"author": "Karl Marx & Friedrich Engels"}'::jsonb, null),
('book', 'The Elements of Style', 4, 'T E O S', '{"author": "William Strunk Jr. & E. B. White"}'::jsonb, null),
('book', 'The Diary of a Young Girl', 6, 'T D O A Y G', '{"author": "Anne Frank"}'::jsonb, null),
('book', 'The Miracle of Mindfulness', 4, 'T M O M', '{"author": "Thích Nhất Hạnh"}'::jsonb, null),
('book', 'The Power of Now', 4, 'T P O N', '{"author": "Eckhart Tolle"}'::jsonb, null);